[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ppz"
version = "0.1.0"
description = "Predicción de Precio Basada en Zonas"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]